apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hermes-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hermes-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "hermes-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hermes-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: {{ include "hermes-operator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: {{ include "hermes-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [/manager]
          args:
            - --health-probe-bind-address=:8081
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:8443
            {{- else }}
            - --metrics-bind-address=0
            {{- end }}
          env:
            - name: RELOADER_IMAGE
              value: {{ include "hermes-operator.reloaderImage" . }}
          ports:
            - containerPort: 8081
              name: health
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - containerPort: 8443
              name: metrics
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.podTemplate }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
